spring.application.name=demo
spring.datasource.url=jdbc:h2:mem:innovatech_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Habilita la consola en /h2-console
spring.h2.console.enabled=true
# 1. Asegúrate de que Hibernate cree las tablas de cero
spring.jpa.hibernate.ddl-auto=create-drop

# 2. Esta es la clave: le dice a Spring que ejecute el import.sql DESPUÉS de crear las tablas
spring.jpa.defer-datasource-initialization=true

# 3. Opcional: Mostrar el SQL en consola para que veas si el insert funciona
spring.jpa.show-sql=true